/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthGroupsRouteImport } from './routes/_auth/groups'
import { Route as AuthApostasRouteImport } from './routes/_auth/apostas'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthGroupsGroupIdRouteImport } from './routes/_auth/groups.$groupId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGroupsRoute = AuthGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApostasRoute = AuthApostasRouteImport.update({
  id: '/apostas',
  path: '/apostas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGroupsGroupIdRoute = AuthGroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AuthGroupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthAdminRoute
  '/apostas': typeof AuthApostasRoute
  '/groups': typeof AuthGroupsRouteWithChildren
  '/groups/$groupId': typeof AuthGroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthAdminRoute
  '/apostas': typeof AuthApostasRoute
  '/groups': typeof AuthGroupsRouteWithChildren
  '/groups/$groupId': typeof AuthGroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/apostas': typeof AuthApostasRoute
  '/_auth/groups': typeof AuthGroupsRouteWithChildren
  '/_auth/groups/$groupId': typeof AuthGroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/admin'
    | '/apostas'
    | '/groups'
    | '/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/admin'
    | '/apostas'
    | '/groups'
    | '/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/reset-password'
    | '/_auth/admin'
    | '/_auth/apostas'
    | '/_auth/groups'
    | '/_auth/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/groups': {
      id: '/_auth/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthGroupsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/apostas': {
      id: '/_auth/apostas'
      path: '/apostas'
      fullPath: '/apostas'
      preLoaderRoute: typeof AuthApostasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/groups/$groupId': {
      id: '/_auth/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthGroupsGroupIdRouteImport
      parentRoute: typeof AuthGroupsRoute
    }
  }
}

interface AuthGroupsRouteChildren {
  AuthGroupsGroupIdRoute: typeof AuthGroupsGroupIdRoute
}

const AuthGroupsRouteChildren: AuthGroupsRouteChildren = {
  AuthGroupsGroupIdRoute: AuthGroupsGroupIdRoute,
}

const AuthGroupsRouteWithChildren = AuthGroupsRoute._addFileChildren(
  AuthGroupsRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthApostasRoute: typeof AuthApostasRoute
  AuthGroupsRoute: typeof AuthGroupsRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthApostasRoute: AuthApostasRoute,
  AuthGroupsRoute: AuthGroupsRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
